version: '3.7'

services:
  terraria:
    image: 'dstmodders/terraria-server:tshock'
    stdin_open: true
    tty: true
    ports:
      - '7777:7777'
      - '7878:7878' # REST API
    volumes:
      - './data/:/data/:rw'
    environment:
      # system parameters
      DISABLE_SUMMARY: 0
      TZ: UTC
      # command-line parameters
      TSHOCK_ADDITIONALPLUGINS: /data/plugins/
      TSHOCK_CONFIGPATH: /data/
      TSHOCK_CRASHDIR: /data/crashes/
      TSHOCK_LOGPATH: /data/logs/
      TSHOCK_WORLDSELECTPATH: /data/worlds/
